name: shieldx
description: ShieldX - Crime Reporting Portal Management System
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Supabase
  supabase_flutter: ^2.5.6

  # Navigation
  go_router: ^13.2.0

  # State Management
  flutter_riverpod: ^2.5.1

  # UI / Design
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  shimmer: ^3.0.0
  fl_chart: ^0.68.0

  # Image
  image_picker: ^1.0.7

  # Utils
  intl: ^0.19.0
  uuid: ^4.3.3
  shared_preferences: ^2.5.5
  flutter_map: ^8.3.0
  latlong2: ^0.9.1
  url_launcher: ^6.3.2
  geolocator: ^14.0.2
  http: ^1.6.0
  flutter_map_location_marker: ^10.2.0
  file_picker: ^11.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
    - assets/icons/
